// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockCourseUpdater is an autogenerated mock type for the CourseUpdater type
type MockCourseUpdater struct {
	mock.Mock
}

type MockCourseUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourseUpdater) EXPECT() *MockCourseUpdater_Expecter {
	return &MockCourseUpdater_Expecter{mock: &_m.Mock}
}

// UpdateCourse provides a mock function with given fields: course
func (_m *MockCourseUpdater) UpdateCourse(course *models.Course) error {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Course) error); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseUpdater_UpdateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCourse'
type MockCourseUpdater_UpdateCourse_Call struct {
	*mock.Call
}

// UpdateCourse is a helper method to define mock.On call
//   - course *models.Course
func (_e *MockCourseUpdater_Expecter) UpdateCourse(course interface{}) *MockCourseUpdater_UpdateCourse_Call {
	return &MockCourseUpdater_UpdateCourse_Call{Call: _e.mock.On("UpdateCourse", course)}
}

func (_c *MockCourseUpdater_UpdateCourse_Call) Run(run func(course *models.Course)) *MockCourseUpdater_UpdateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Course))
	})
	return _c
}

func (_c *MockCourseUpdater_UpdateCourse_Call) Return(_a0 error) *MockCourseUpdater_UpdateCourse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseUpdater_UpdateCourse_Call) RunAndReturn(run func(*models.Course) error) *MockCourseUpdater_UpdateCourse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourseUpdater creates a new instance of MockCourseUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourseUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourseUpdater {
	mock := &MockCourseUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
