// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockCoursesLister is an autogenerated mock type for the CoursesLister type
type MockCoursesLister struct {
	mock.Mock
}

type MockCoursesLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoursesLister) EXPECT() *MockCoursesLister_Expecter {
	return &MockCoursesLister_Expecter{mock: &_m.Mock}
}

// GetAllCourses provides a mock function with no fields
func (_m *MockCoursesLister) GetAllCourses() ([]*models.Course, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCourses")
	}

	var r0 []*models.Course
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Course, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Course); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Course)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoursesLister_GetAllCourses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCourses'
type MockCoursesLister_GetAllCourses_Call struct {
	*mock.Call
}

// GetAllCourses is a helper method to define mock.On call
func (_e *MockCoursesLister_Expecter) GetAllCourses() *MockCoursesLister_GetAllCourses_Call {
	return &MockCoursesLister_GetAllCourses_Call{Call: _e.mock.On("GetAllCourses")}
}

func (_c *MockCoursesLister_GetAllCourses_Call) Run(run func()) *MockCoursesLister_GetAllCourses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoursesLister_GetAllCourses_Call) Return(_a0 []*models.Course, _a1 error) *MockCoursesLister_GetAllCourses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoursesLister_GetAllCourses_Call) RunAndReturn(run func() ([]*models.Course, error)) *MockCoursesLister_GetAllCourses_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCoursesLister creates a new instance of MockCoursesLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoursesLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoursesLister {
	mock := &MockCoursesLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
