// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockCourseValidator is an autogenerated mock type for the CourseValidator type
type MockCourseValidator struct {
	mock.Mock
}

type MockCourseValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourseValidator) EXPECT() *MockCourseValidator_Expecter {
	return &MockCourseValidator_Expecter{mock: &_m.Mock}
}

// GetCourseByID provides a mock function with given fields: id
func (_m *MockCourseValidator) GetCourseByID(id int) (*models.Course, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseByID")
	}

	var r0 *models.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Course, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Course); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseValidator_GetCourseByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourseByID'
type MockCourseValidator_GetCourseByID_Call struct {
	*mock.Call
}

// GetCourseByID is a helper method to define mock.On call
//   - id int
func (_e *MockCourseValidator_Expecter) GetCourseByID(id interface{}) *MockCourseValidator_GetCourseByID_Call {
	return &MockCourseValidator_GetCourseByID_Call{Call: _e.mock.On("GetCourseByID", id)}
}

func (_c *MockCourseValidator_GetCourseByID_Call) Run(run func(id int)) *MockCourseValidator_GetCourseByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCourseValidator_GetCourseByID_Call) Return(_a0 *models.Course, _a1 error) *MockCourseValidator_GetCourseByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseValidator_GetCourseByID_Call) RunAndReturn(run func(int) (*models.Course, error)) *MockCourseValidator_GetCourseByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourseValidator creates a new instance of MockCourseValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourseValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourseValidator {
	mock := &MockCourseValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
