// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockCourseDeleter is an autogenerated mock type for the CourseDeleter type
type MockCourseDeleter struct {
	mock.Mock
}

type MockCourseDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourseDeleter) EXPECT() *MockCourseDeleter_Expecter {
	return &MockCourseDeleter_Expecter{mock: &_m.Mock}
}

// DeleteCourse provides a mock function with given fields: id
func (_m *MockCourseDeleter) DeleteCourse(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseDeleter_DeleteCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCourse'
type MockCourseDeleter_DeleteCourse_Call struct {
	*mock.Call
}

// DeleteCourse is a helper method to define mock.On call
//   - id int
func (_e *MockCourseDeleter_Expecter) DeleteCourse(id interface{}) *MockCourseDeleter_DeleteCourse_Call {
	return &MockCourseDeleter_DeleteCourse_Call{Call: _e.mock.On("DeleteCourse", id)}
}

func (_c *MockCourseDeleter_DeleteCourse_Call) Run(run func(id int)) *MockCourseDeleter_DeleteCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCourseDeleter_DeleteCourse_Call) Return(_a0 error) *MockCourseDeleter_DeleteCourse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseDeleter_DeleteCourse_Call) RunAndReturn(run func(int) error) *MockCourseDeleter_DeleteCourse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourseDeleter creates a new instance of MockCourseDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourseDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourseDeleter {
	mock := &MockCourseDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
