// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTeacherValidator is an autogenerated mock type for the TeacherValidator type
type MockTeacherValidator struct {
	mock.Mock
}

type MockTeacherValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeacherValidator) EXPECT() *MockTeacherValidator_Expecter {
	return &MockTeacherValidator_Expecter{mock: &_m.Mock}
}

// GetTeacherByID provides a mock function with given fields: id
func (_m *MockTeacherValidator) GetTeacherByID(id int) (*models.Teacher, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeacherByID")
	}

	var r0 *models.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Teacher, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Teacher); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Teacher)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeacherValidator_GetTeacherByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeacherByID'
type MockTeacherValidator_GetTeacherByID_Call struct {
	*mock.Call
}

// GetTeacherByID is a helper method to define mock.On call
//   - id int
func (_e *MockTeacherValidator_Expecter) GetTeacherByID(id interface{}) *MockTeacherValidator_GetTeacherByID_Call {
	return &MockTeacherValidator_GetTeacherByID_Call{Call: _e.mock.On("GetTeacherByID", id)}
}

func (_c *MockTeacherValidator_GetTeacherByID_Call) Run(run func(id int)) *MockTeacherValidator_GetTeacherByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTeacherValidator_GetTeacherByID_Call) Return(_a0 *models.Teacher, _a1 error) *MockTeacherValidator_GetTeacherByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeacherValidator_GetTeacherByID_Call) RunAndReturn(run func(int) (*models.Teacher, error)) *MockTeacherValidator_GetTeacherByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeacherValidator creates a new instance of MockTeacherValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeacherValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeacherValidator {
	mock := &MockTeacherValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
