// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockCourseCreator is an autogenerated mock type for the CourseCreator type
type MockCourseCreator struct {
	mock.Mock
}

type MockCourseCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourseCreator) EXPECT() *MockCourseCreator_Expecter {
	return &MockCourseCreator_Expecter{mock: &_m.Mock}
}

// CreateCourse provides a mock function with given fields: course
func (_m *MockCourseCreator) CreateCourse(course *models.Course) (int, error) {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Course) (int, error)); ok {
		return rf(course)
	}
	if rf, ok := ret.Get(0).(func(*models.Course) int); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*models.Course) error); ok {
		r1 = rf(course)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseCreator_CreateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourse'
type MockCourseCreator_CreateCourse_Call struct {
	*mock.Call
}

// CreateCourse is a helper method to define mock.On call
//   - course *models.Course
func (_e *MockCourseCreator_Expecter) CreateCourse(course interface{}) *MockCourseCreator_CreateCourse_Call {
	return &MockCourseCreator_CreateCourse_Call{Call: _e.mock.On("CreateCourse", course)}
}

func (_c *MockCourseCreator_CreateCourse_Call) Run(run func(course *models.Course)) *MockCourseCreator_CreateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Course))
	})
	return _c
}

func (_c *MockCourseCreator_CreateCourse_Call) Return(_a0 int, _a1 error) *MockCourseCreator_CreateCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseCreator_CreateCourse_Call) RunAndReturn(run func(*models.Course) (int, error)) *MockCourseCreator_CreateCourse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourseCreator creates a new instance of MockCourseCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourseCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourseCreator {
	mock := &MockCourseCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
