// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockStudentCreator is an autogenerated mock type for the StudentCreator type
type MockStudentCreator struct {
	mock.Mock
}

type MockStudentCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudentCreator) EXPECT() *MockStudentCreator_Expecter {
	return &MockStudentCreator_Expecter{mock: &_m.Mock}
}

// CreateStudent provides a mock function with given fields: student
func (_m *MockStudentCreator) CreateStudent(student *models.Student) (int, error) {
	ret := _m.Called(student)

	if len(ret) == 0 {
		panic("no return value specified for CreateStudent")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Student) (int, error)); ok {
		return rf(student)
	}
	if rf, ok := ret.Get(0).(func(*models.Student) int); ok {
		r0 = rf(student)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*models.Student) error); ok {
		r1 = rf(student)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentCreator_CreateStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStudent'
type MockStudentCreator_CreateStudent_Call struct {
	*mock.Call
}

// CreateStudent is a helper method to define mock.On call
//   - student *models.Student
func (_e *MockStudentCreator_Expecter) CreateStudent(student interface{}) *MockStudentCreator_CreateStudent_Call {
	return &MockStudentCreator_CreateStudent_Call{Call: _e.mock.On("CreateStudent", student)}
}

func (_c *MockStudentCreator_CreateStudent_Call) Run(run func(student *models.Student)) *MockStudentCreator_CreateStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Student))
	})
	return _c
}

func (_c *MockStudentCreator_CreateStudent_Call) Return(_a0 int, _a1 error) *MockStudentCreator_CreateStudent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentCreator_CreateStudent_Call) RunAndReturn(run func(*models.Student) (int, error)) *MockStudentCreator_CreateStudent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudentCreator creates a new instance of MockStudentCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudentCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudentCreator {
	mock := &MockStudentCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
