// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStudentDeleter is an autogenerated mock type for the StudentDeleter type
type MockStudentDeleter struct {
	mock.Mock
}

type MockStudentDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudentDeleter) EXPECT() *MockStudentDeleter_Expecter {
	return &MockStudentDeleter_Expecter{mock: &_m.Mock}
}

// DeleteStudent provides a mock function with given fields: id
func (_m *MockStudentDeleter) DeleteStudent(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStudentDeleter_DeleteStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStudent'
type MockStudentDeleter_DeleteStudent_Call struct {
	*mock.Call
}

// DeleteStudent is a helper method to define mock.On call
//   - id int
func (_e *MockStudentDeleter_Expecter) DeleteStudent(id interface{}) *MockStudentDeleter_DeleteStudent_Call {
	return &MockStudentDeleter_DeleteStudent_Call{Call: _e.mock.On("DeleteStudent", id)}
}

func (_c *MockStudentDeleter_DeleteStudent_Call) Run(run func(id int)) *MockStudentDeleter_DeleteStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockStudentDeleter_DeleteStudent_Call) Return(_a0 error) *MockStudentDeleter_DeleteStudent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStudentDeleter_DeleteStudent_Call) RunAndReturn(run func(int) error) *MockStudentDeleter_DeleteStudent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudentDeleter creates a new instance of MockStudentDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudentDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudentDeleter {
	mock := &MockStudentDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
