// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockStudentUpdater is an autogenerated mock type for the StudentUpdater type
type MockStudentUpdater struct {
	mock.Mock
}

type MockStudentUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudentUpdater) EXPECT() *MockStudentUpdater_Expecter {
	return &MockStudentUpdater_Expecter{mock: &_m.Mock}
}

// UpdateStudent provides a mock function with given fields: student
func (_m *MockStudentUpdater) UpdateStudent(student *models.Student) error {
	ret := _m.Called(student)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Student) error); ok {
		r0 = rf(student)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStudentUpdater_UpdateStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStudent'
type MockStudentUpdater_UpdateStudent_Call struct {
	*mock.Call
}

// UpdateStudent is a helper method to define mock.On call
//   - student *models.Student
func (_e *MockStudentUpdater_Expecter) UpdateStudent(student interface{}) *MockStudentUpdater_UpdateStudent_Call {
	return &MockStudentUpdater_UpdateStudent_Call{Call: _e.mock.On("UpdateStudent", student)}
}

func (_c *MockStudentUpdater_UpdateStudent_Call) Run(run func(student *models.Student)) *MockStudentUpdater_UpdateStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Student))
	})
	return _c
}

func (_c *MockStudentUpdater_UpdateStudent_Call) Return(_a0 error) *MockStudentUpdater_UpdateStudent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStudentUpdater_UpdateStudent_Call) RunAndReturn(run func(*models.Student) error) *MockStudentUpdater_UpdateStudent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudentUpdater creates a new instance of MockStudentUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudentUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudentUpdater {
	mock := &MockStudentUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
