// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockStudentsLister is an autogenerated mock type for the StudentsLister type
type MockStudentsLister struct {
	mock.Mock
}

type MockStudentsLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudentsLister) EXPECT() *MockStudentsLister_Expecter {
	return &MockStudentsLister_Expecter{mock: &_m.Mock}
}

// GetAllStudents provides a mock function with no fields
func (_m *MockStudentsLister) GetAllStudents() ([]*models.Student, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStudents")
	}

	var r0 []*models.Student
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Student, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Student); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Student)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentsLister_GetAllStudents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStudents'
type MockStudentsLister_GetAllStudents_Call struct {
	*mock.Call
}

// GetAllStudents is a helper method to define mock.On call
func (_e *MockStudentsLister_Expecter) GetAllStudents() *MockStudentsLister_GetAllStudents_Call {
	return &MockStudentsLister_GetAllStudents_Call{Call: _e.mock.On("GetAllStudents")}
}

func (_c *MockStudentsLister_GetAllStudents_Call) Run(run func()) *MockStudentsLister_GetAllStudents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStudentsLister_GetAllStudents_Call) Return(_a0 []*models.Student, _a1 error) *MockStudentsLister_GetAllStudents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentsLister_GetAllStudents_Call) RunAndReturn(run func() ([]*models.Student, error)) *MockStudentsLister_GetAllStudents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudentsLister creates a new instance of MockStudentsLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudentsLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudentsLister {
	mock := &MockStudentsLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
