// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockStudentValidator is an autogenerated mock type for the StudentValidator type
type MockStudentValidator struct {
	mock.Mock
}

type MockStudentValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudentValidator) EXPECT() *MockStudentValidator_Expecter {
	return &MockStudentValidator_Expecter{mock: &_m.Mock}
}

// GetStudentByID provides a mock function with given fields: id
func (_m *MockStudentValidator) GetStudentByID(id int) (*models.Student, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentByID")
	}

	var r0 *models.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Student, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Student); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentValidator_GetStudentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudentByID'
type MockStudentValidator_GetStudentByID_Call struct {
	*mock.Call
}

// GetStudentByID is a helper method to define mock.On call
//   - id int
func (_e *MockStudentValidator_Expecter) GetStudentByID(id interface{}) *MockStudentValidator_GetStudentByID_Call {
	return &MockStudentValidator_GetStudentByID_Call{Call: _e.mock.On("GetStudentByID", id)}
}

func (_c *MockStudentValidator_GetStudentByID_Call) Run(run func(id int)) *MockStudentValidator_GetStudentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockStudentValidator_GetStudentByID_Call) Return(_a0 *models.Student, _a1 error) *MockStudentValidator_GetStudentByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentValidator_GetStudentByID_Call) RunAndReturn(run func(int) (*models.Student, error)) *MockStudentValidator_GetStudentByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudentValidator creates a new instance of MockStudentValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudentValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudentValidator {
	mock := &MockStudentValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
