// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockEnrollmentCreator is an autogenerated mock type for the EnrollmentCreator type
type MockEnrollmentCreator struct {
	mock.Mock
}

type MockEnrollmentCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnrollmentCreator) EXPECT() *MockEnrollmentCreator_Expecter {
	return &MockEnrollmentCreator_Expecter{mock: &_m.Mock}
}

// CreateEnrollment provides a mock function with given fields: enrollment
func (_m *MockEnrollmentCreator) CreateEnrollment(enrollment *models.Enrollment) error {
	ret := _m.Called(enrollment)

	if len(ret) == 0 {
		panic("no return value specified for CreateEnrollment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Enrollment) error); ok {
		r0 = rf(enrollment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEnrollmentCreator_CreateEnrollment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEnrollment'
type MockEnrollmentCreator_CreateEnrollment_Call struct {
	*mock.Call
}

// CreateEnrollment is a helper method to define mock.On call
//   - enrollment *models.Enrollment
func (_e *MockEnrollmentCreator_Expecter) CreateEnrollment(enrollment interface{}) *MockEnrollmentCreator_CreateEnrollment_Call {
	return &MockEnrollmentCreator_CreateEnrollment_Call{Call: _e.mock.On("CreateEnrollment", enrollment)}
}

func (_c *MockEnrollmentCreator_CreateEnrollment_Call) Run(run func(enrollment *models.Enrollment)) *MockEnrollmentCreator_CreateEnrollment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Enrollment))
	})
	return _c
}

func (_c *MockEnrollmentCreator_CreateEnrollment_Call) Return(_a0 error) *MockEnrollmentCreator_CreateEnrollment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnrollmentCreator_CreateEnrollment_Call) RunAndReturn(run func(*models.Enrollment) error) *MockEnrollmentCreator_CreateEnrollment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnrollmentCreator creates a new instance of MockEnrollmentCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnrollmentCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnrollmentCreator {
	mock := &MockEnrollmentCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
