// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockEnrollmentDeleter is an autogenerated mock type for the EnrollmentDeleter type
type MockEnrollmentDeleter struct {
	mock.Mock
}

type MockEnrollmentDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnrollmentDeleter) EXPECT() *MockEnrollmentDeleter_Expecter {
	return &MockEnrollmentDeleter_Expecter{mock: &_m.Mock}
}

// DeleteEnrollment provides a mock function with given fields: studentID, courseID
func (_m *MockEnrollmentDeleter) DeleteEnrollment(studentID int, courseID int) error {
	ret := _m.Called(studentID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEnrollment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(studentID, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEnrollmentDeleter_DeleteEnrollment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEnrollment'
type MockEnrollmentDeleter_DeleteEnrollment_Call struct {
	*mock.Call
}

// DeleteEnrollment is a helper method to define mock.On call
//   - studentID int
//   - courseID int
func (_e *MockEnrollmentDeleter_Expecter) DeleteEnrollment(studentID interface{}, courseID interface{}) *MockEnrollmentDeleter_DeleteEnrollment_Call {
	return &MockEnrollmentDeleter_DeleteEnrollment_Call{Call: _e.mock.On("DeleteEnrollment", studentID, courseID)}
}

func (_c *MockEnrollmentDeleter_DeleteEnrollment_Call) Run(run func(studentID int, courseID int)) *MockEnrollmentDeleter_DeleteEnrollment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockEnrollmentDeleter_DeleteEnrollment_Call) Return(_a0 error) *MockEnrollmentDeleter_DeleteEnrollment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnrollmentDeleter_DeleteEnrollment_Call) RunAndReturn(run func(int, int) error) *MockEnrollmentDeleter_DeleteEnrollment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnrollmentDeleter creates a new instance of MockEnrollmentDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnrollmentDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnrollmentDeleter {
	mock := &MockEnrollmentDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
