// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTeacherDeleter is an autogenerated mock type for the TeacherDeleter type
type MockTeacherDeleter struct {
	mock.Mock
}

type MockTeacherDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeacherDeleter) EXPECT() *MockTeacherDeleter_Expecter {
	return &MockTeacherDeleter_Expecter{mock: &_m.Mock}
}

// DeleteTeacher provides a mock function with given fields: id
func (_m *MockTeacherDeleter) DeleteTeacher(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeacher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeacherDeleter_DeleteTeacher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeacher'
type MockTeacherDeleter_DeleteTeacher_Call struct {
	*mock.Call
}

// DeleteTeacher is a helper method to define mock.On call
//   - id int
func (_e *MockTeacherDeleter_Expecter) DeleteTeacher(id interface{}) *MockTeacherDeleter_DeleteTeacher_Call {
	return &MockTeacherDeleter_DeleteTeacher_Call{Call: _e.mock.On("DeleteTeacher", id)}
}

func (_c *MockTeacherDeleter_DeleteTeacher_Call) Run(run func(id int)) *MockTeacherDeleter_DeleteTeacher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTeacherDeleter_DeleteTeacher_Call) Return(_a0 error) *MockTeacherDeleter_DeleteTeacher_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeacherDeleter_DeleteTeacher_Call) RunAndReturn(run func(int) error) *MockTeacherDeleter_DeleteTeacher_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeacherDeleter creates a new instance of MockTeacherDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeacherDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeacherDeleter {
	mock := &MockTeacherDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
