// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTeacherGetter is an autogenerated mock type for the TeacherGetter type
type MockTeacherGetter struct {
	mock.Mock
}

type MockTeacherGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeacherGetter) EXPECT() *MockTeacherGetter_Expecter {
	return &MockTeacherGetter_Expecter{mock: &_m.Mock}
}

// GetTeacherByID provides a mock function with given fields: id
func (_m *MockTeacherGetter) GetTeacherByID(id int) (*models.Teacher, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeacherByID")
	}

	var r0 *models.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Teacher, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Teacher); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Teacher)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeacherGetter_GetTeacherByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeacherByID'
type MockTeacherGetter_GetTeacherByID_Call struct {
	*mock.Call
}

// GetTeacherByID is a helper method to define mock.On call
//   - id int
func (_e *MockTeacherGetter_Expecter) GetTeacherByID(id interface{}) *MockTeacherGetter_GetTeacherByID_Call {
	return &MockTeacherGetter_GetTeacherByID_Call{Call: _e.mock.On("GetTeacherByID", id)}
}

func (_c *MockTeacherGetter_GetTeacherByID_Call) Run(run func(id int)) *MockTeacherGetter_GetTeacherByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTeacherGetter_GetTeacherByID_Call) Return(_a0 *models.Teacher, _a1 error) *MockTeacherGetter_GetTeacherByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeacherGetter_GetTeacherByID_Call) RunAndReturn(run func(int) (*models.Teacher, error)) *MockTeacherGetter_GetTeacherByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeacherGetter creates a new instance of MockTeacherGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeacherGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeacherGetter {
	mock := &MockTeacherGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
