// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTeacherCreator is an autogenerated mock type for the TeacherCreator type
type MockTeacherCreator struct {
	mock.Mock
}

type MockTeacherCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeacherCreator) EXPECT() *MockTeacherCreator_Expecter {
	return &MockTeacherCreator_Expecter{mock: &_m.Mock}
}

// CreateTeacher provides a mock function with given fields: teacher
func (_m *MockTeacherCreator) CreateTeacher(teacher *models.Teacher) (int, error) {
	ret := _m.Called(teacher)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeacher")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Teacher) (int, error)); ok {
		return rf(teacher)
	}
	if rf, ok := ret.Get(0).(func(*models.Teacher) int); ok {
		r0 = rf(teacher)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*models.Teacher) error); ok {
		r1 = rf(teacher)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeacherCreator_CreateTeacher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeacher'
type MockTeacherCreator_CreateTeacher_Call struct {
	*mock.Call
}

// CreateTeacher is a helper method to define mock.On call
//   - teacher *models.Teacher
func (_e *MockTeacherCreator_Expecter) CreateTeacher(teacher interface{}) *MockTeacherCreator_CreateTeacher_Call {
	return &MockTeacherCreator_CreateTeacher_Call{Call: _e.mock.On("CreateTeacher", teacher)}
}

func (_c *MockTeacherCreator_CreateTeacher_Call) Run(run func(teacher *models.Teacher)) *MockTeacherCreator_CreateTeacher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Teacher))
	})
	return _c
}

func (_c *MockTeacherCreator_CreateTeacher_Call) Return(_a0 int, _a1 error) *MockTeacherCreator_CreateTeacher_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeacherCreator_CreateTeacher_Call) RunAndReturn(run func(*models.Teacher) (int, error)) *MockTeacherCreator_CreateTeacher_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeacherCreator creates a new instance of MockTeacherCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeacherCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeacherCreator {
	mock := &MockTeacherCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
