// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTeacherUpdater is an autogenerated mock type for the TeacherUpdater type
type MockTeacherUpdater struct {
	mock.Mock
}

type MockTeacherUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeacherUpdater) EXPECT() *MockTeacherUpdater_Expecter {
	return &MockTeacherUpdater_Expecter{mock: &_m.Mock}
}

// UpdateTeacher provides a mock function with given fields: teacher
func (_m *MockTeacherUpdater) UpdateTeacher(teacher *models.Teacher) error {
	ret := _m.Called(teacher)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeacher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Teacher) error); ok {
		r0 = rf(teacher)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeacherUpdater_UpdateTeacher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTeacher'
type MockTeacherUpdater_UpdateTeacher_Call struct {
	*mock.Call
}

// UpdateTeacher is a helper method to define mock.On call
//   - teacher *models.Teacher
func (_e *MockTeacherUpdater_Expecter) UpdateTeacher(teacher interface{}) *MockTeacherUpdater_UpdateTeacher_Call {
	return &MockTeacherUpdater_UpdateTeacher_Call{Call: _e.mock.On("UpdateTeacher", teacher)}
}

func (_c *MockTeacherUpdater_UpdateTeacher_Call) Run(run func(teacher *models.Teacher)) *MockTeacherUpdater_UpdateTeacher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Teacher))
	})
	return _c
}

func (_c *MockTeacherUpdater_UpdateTeacher_Call) Return(_a0 error) *MockTeacherUpdater_UpdateTeacher_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeacherUpdater_UpdateTeacher_Call) RunAndReturn(run func(*models.Teacher) error) *MockTeacherUpdater_UpdateTeacher_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeacherUpdater creates a new instance of MockTeacherUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeacherUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeacherUpdater {
	mock := &MockTeacherUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
