// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "simple-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTeachersLister is an autogenerated mock type for the TeachersLister type
type MockTeachersLister struct {
	mock.Mock
}

type MockTeachersLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeachersLister) EXPECT() *MockTeachersLister_Expecter {
	return &MockTeachersLister_Expecter{mock: &_m.Mock}
}

// GetAllTeachers provides a mock function with no fields
func (_m *MockTeachersLister) GetAllTeachers() ([]*models.Teacher, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTeachers")
	}

	var r0 []*models.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Teacher, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Teacher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Teacher)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeachersLister_GetAllTeachers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTeachers'
type MockTeachersLister_GetAllTeachers_Call struct {
	*mock.Call
}

// GetAllTeachers is a helper method to define mock.On call
func (_e *MockTeachersLister_Expecter) GetAllTeachers() *MockTeachersLister_GetAllTeachers_Call {
	return &MockTeachersLister_GetAllTeachers_Call{Call: _e.mock.On("GetAllTeachers")}
}

func (_c *MockTeachersLister_GetAllTeachers_Call) Run(run func()) *MockTeachersLister_GetAllTeachers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTeachersLister_GetAllTeachers_Call) Return(_a0 []*models.Teacher, _a1 error) *MockTeachersLister_GetAllTeachers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeachersLister_GetAllTeachers_Call) RunAndReturn(run func() ([]*models.Teacher, error)) *MockTeachersLister_GetAllTeachers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeachersLister creates a new instance of MockTeachersLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeachersLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeachersLister {
	mock := &MockTeachersLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
